language: node_js
node_js:
  - 10
cache:
  npm: true
  directories:
    - ~/.cache
install:
  - yarn install --frozen-lockfile
before_script:
  - yarn build
  - yarn start
script:
  - yarn ci:e2e

notifications:
  email: false
